version: "3"

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev@123456
      POSTGRES_DB: dev
    networks:
      - backend

networks:
  backend:
