version: "3.8"
services:
  go_app:
    container_name: go_app
    build:
      context: ../..
      dockerfile: .docker/prd/Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: always
    networks:
      - boilerplate_network
    environment:
      - ENVIRONMENT=Dev
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_DATABASE=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - ../../.env
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    tty: true
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data:/var/lib/postgresql/data/
    networks:
      - boilerplate_network
    env_file:
      - ../../.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
networks:
  boilerplate_network:
    name: boilerplate_network
    driver: bridge